title: Agroé – Pôle Agroalimentaire
logo: 'agroe.png'
description: Accompagne les entreprises régionales dans la révolution numérique et sociétale.
baseurl: "/agroe-jekyll" # the subpath of your site, e.g. /blog
url: "https://timotte1984.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Agroé
  image:
  job: Pour une industrie agroalimentaire engagée et connectée
  bio: Agroé accompagne les entreprises agrolaimentaires de la région Hauts-de-France dans la structuration et la valorisation de leurs démarches de responsabilité sociétale des entreprises (RSE) et de management de l'information.
  email: contact@agroe.com


# Contact links
contact:
  - name: Twitter
    link: https://twitter.com/agroe_i?lang=fr
  - name: Facebook
    link: https://www.facebook.com/profile.php?id=100011465318774&__tn__=%2CdK-R-R&eid=ARAQfQrUTT6V9lhViLl_dnCVOtw7tD2PFWkUzm5qUMhX1QGtuQ2_VfV1IWD9x1o7tPT6gJdH9SsaFcBN&fref=mentions
  - name: LinkedIn
    link: https://www.linkedin.com/company/agroe62/?viewAsMember=true
  - name: Youtube
    link: https://www.youtube.com/channel/UCinUo8-stq3edw4Ozo2qRAg/


# Comment Section (Disqus)
disqus-identifier: pleagro # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-140671144-2 # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
